var crypto = {
  _id: "Github-CryptoRepo-RecentUpdated",
  startUrl: [
    "https://github.com/search?q=Ethereum&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Dogecoin&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Solana&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Polygon&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Fantom&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Moonriver&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Avalanche&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Bitcoin+SV&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Bitcoin+Gold&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=VeChain&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Huobi+ECO&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Bitcoin+Cash&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Litecoin&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Dash&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Blockchain&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Cryptocurrency&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Altcoin&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Token&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Decentralization&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Smart+Contract&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Mining&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Wallet&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Ledger&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Exchange&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=ICO&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=DeFi&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=NFT&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Gas+Fees&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Staking&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=FOMO&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=FUD&s=updated&o=desc&type=repositories",
    "https://github.com/search?q=Halving&s=updated&o=desc&type=repositories",
  ],
};

// Recuriters
var recuriters = "https://github.com/search?q=Recruiter&type=users";
